### ISSUE TITLE
Pętle - jeszcze raz stany.

### ISSUE THREAD

**Issue by Cosiek** [ewenement/prezenty#11]
Mamy dwie listy:

```
lista1 = [[1,2,3], [4,5], [6,7]]
lista2 = ['a', 'b', 'c']
```

Podaj wartości `cos`, `cos_mniejsze`, `cos_inne` w  punktach pkt1, pkt2, pkt3, dla kolejnych iteracji.

```
{% for cos in lista1 %}
    pkt1
    {% for cos_mniejsze in cos %}
        pkt2
    {% endfor %}

    {% for cos_inne in lista2 %}
        pkt3
    {% endfor %}
{% endfor %}
```

**Comment by Cosiek** [comment]
@ewenement - :bullettrain_front:

**Comment by ewenement** [comment]
pkt1 - 3,
pkt2 - 7,
pkt3 - 3

**Comment by ewenement** [comment]
pkt 3 -- 9!!
![p_20151209_160942](https://cloud.githubusercontent.com/assets/7847033/11713298/ce340ab2-9f32-11e5-9510-78d57e9b0419.jpg)
![p_20151209_160929](https://cloud.githubusercontent.com/assets/7847033/11713299/d033e6f2-9f32-11e5-9194-b7f9fc20f053.jpg)
