### ISSUE TITLE
Praca domowa 1 - główne kontenery

### ISSUE THREAD

**Issue by Cosiek** [ewenement/prezenty#3]
Chcemy mieć dość standardowo zbudowaną stronę. Powinna się składać z:
- nagłówka (powiedzmy miejsce na logo)
- menu nawigacyjnego
- kontenera na treść
- stopki.

Każdy z tych elementów ma być elementem `<div>` o ustalonych: szerokości wysokości, kolorze tła.
(może być przy pomocy atrybutu style - `<div style="width: 200px">`).

Waże, żeby poszczególne div-y znalazły się we właściwych templatkach oraz żeby `{% block body %}` znalazł się we właściwym divie.

**Comment by Cosiek** [comment]
@ewenement :trolleybus:

**Comment by ewenement** [comment]
Tak sobie patrzę i chuj rozumię :D

**Comment by ewenement** [comment]
już wiem (note to myself) - chodzi o to, że w base jest wszystko to jak ma strona wyglądać w ogóle (każda podstrona i odnośnik, podnośnik i zanośnik). OK. (% block %) po przejściu na inną podstronę spowoduje, że strona będzie taka sama ale ten ważny element na danej podstronie będzie inny (czyli po kliknięciu ze str gównej na linka "cipka" przechodzi do "ewas_gift_list.html. Ta strona ma swoją templatkę, którą on wczytuje w base i dzięki temu na stronie jest wczytany element tejże strony /lista/).
