### ISSUE TITLE
Praca domowa 2 - wyświetlanie listy prezentów.

### ISSUE THREAD

**Issue by Cosiek** [ewenement/prezenty#4]
Pod adresem [http://127.0.0.1:8095/lista_ewy](http://127.0.0.1:8095/lista_ewy) wystawiony jest widok, który przekazuje do templatki listę, dostępną pod nazwą `gifts`. Każdy z elementów tej listy, sam w sobie jest listą, mającą postać: `[id, nazwa, cena, gdzie_kupić]` (np. `[1, 'wąsy', 0.99, 'hipster.com.net.waw.org.eu.pl']`)

Wyświetlić w tym widoku (templatka `ewas_gift_list.html`) listę prezentów, posługując się tagami `<ul>` oraz `<li>`. Gotowa lista powinna wyglądać mniej więcej tak:
- wąsy - 0.99 zł - hipster.com.net.waw.org.eu.pl
- Piwo - 5 zł - www.sikacz.pl
- Wino patykiem pisane - 3 zł - www.sikacz.pl

Jeżeli element dostępny od nazwą `prezent` jest listą, to żeby wyświetlić pierwszy element prezentu, trzeba posłużyć się indeksem (czyli `{{ prezent[0] }}` wyświetli pierwszy element listy, `{{ prezent[1] }}` wyświetli drugi itd.)

**Comment by Cosiek** [comment]
@ewenement :articulated_lorry:

**Comment by ewenement** [comment]
- i zł trzeba było wstawić ręcznie
